grpc/grpc-swift-protobuf

Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
Motivation:
The names of generated types was changed in the upstream code gen module so our tests now fail.
Modifications:
- Update generated tests.
Result:
- Tests pass
=> Update tests to reflect codegen changes

.spi.yml, CONTRIBUTING.md, README.md, SECURITY.md, Sources/GRPCProtobuf/Documentation.docc/Documentation.md
Motivation:
We should have a README to explain what the package is and should point to docs we publish to the Swift Package Index.
Modifications:
- Add a README
- Add a .spi.yml
- Add a DocC catalog
Result:
More docs
=> Add DocC catalog and README

Package.swift
Motivation:
Core components of grpc-swift v2 require API from the latest SDKs. This causes a proliferation of availability annotations through our API. Rather than doing this we can set the minimum platforms in the package manifest.
Modifications:
- Remove availability annotations
- Set platforms in the package manifest
Result:
- Less boilerplate
- Users must set platforms in their package manifest
=> Add deployment targets to the package manifest

Sources/GRPCProtobufCodeGen/CamelCaser.swift, Sources/GRPCProtobufCodeGen/ProtobufCodeGenParser.swift, Tests/GRPCProtobufCodeGenTests/CamelCaserTests.swift
Motivation:
Given a method name, say `ImportCSV`, from a `.proto` file, the generated method name in upper and lower camel case is `ImportCsv` and `importCsv` respectively. The generated method name (which is already expected to be in upper camel case) in upper and lower camel case should be `ImportCSV` and `importCSV` respectively.
Modifications:
- Replace the method used for generating service and method names in lower camel case with a newly implemented method.
- Do not convert the base names of services and methods to upper camel case as they are expected to already be in upper camel case.
Result:
The casing of service and method names will be preserved when generating stubs.
=> Fix casing of generated services and methods

Package.swift
We should depend on `grpc-swift/main` for now to make sure that everything works cross-package.
This PR changes `grpc-swift-protobuf` to depend on `main` for `grpc-swift`. It also fixes some tests as a result of adding the cancellation handler to the API.
`grpc-swift-extras` builds with the latest `grpc-swift` changes.
=> Depend on `grpc-swift/main`

Package.swift, Sources/protoc-gen-grpc-swift/Options.swift
Motivation:
The test targets don't set the same Swift as the library targets. There's no reason for them not to.
Modifications:
- Apply default settings to test targets.
- Add missing 'any'
Result:
Test targets use Swift 6 language mode, explicit existential any, and internal imports by default
=> Add more build settings to test targets

Sources/GRPCProtobufCodeGen/ProtobufCodeGenParser.swift, Tests/GRPCProtobufCodeGenTests/ProtobufCodeGenParserTests.swift, Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
Motivation:
The 'SwiftProtobuf' import was missing from generated code.
Modifications:
- Always generate an import for 'SwiftProtobuf'
Result:
Import are more correct
=> Always include the 'SwiftProtobuf' import in generated code

Sources/protoc-gen-grpc-swift/Options.swift
Motivation:
The protoc-gen-grpc-swift plugin has a few boolean options which currently require a lowercased value. This is overly strict, the casing of "true"/"false" shouldn't matter.
Modifications:
- Ignore case for boolean optioned values
Result:
Easier to use protoc-gen-grpc-swift
=> Ignore case for boolean option values in protoc-gen-grpc-swift

Sources/GRPCProtobufCodeGen/ProtobufCodeGenParser.swift
Motivation:
The fix in #17 relies on `SwiftProtobufPluginLibrary`'s `WellKnownType` type including all protos bundled by `SwiftProtobuf`, this turns out not to be true so in some case (like using the "Empty" proto) an import was missing.
Modifications:
- Use the "isBundleProto" API which better suits our needs
- Update test to use type which would fail test before fix
Result:
Better code gen
=> Make check for bundled protos more resilient

Sources/GRPCProtobufCodeGen/ProtobufCodeGenParser.swift, Sources/protoc-gen-grpc-swift/GenerateGRPC.swift, Sources/protoc-gen-grpc-swift/Options.swift
Motivation:
FoundationEssentials only includes ... the essentials. We should use it where available.
Modifications:
- Remove unused Foundation imports
- Replace a Foundation import with a FoundationEssentials import
Result:
Smaller dependency set
=> Use FoundationEssentials where possible

Sources/GRPCProtobuf/Coding.swift, Sources/GRPCProtobuf/ContiguousBytesAdapter.swift, Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift, Tests/GRPCProtobufTests/Errors/Generated/error-service.grpc.swift, Tests/GRPCProtobufTests/ProtobufCodingTests.swift
Motivation:
The core package made a few changes allowing for transport to define an associated bag-of-bytes types so that they can avoid copying to and from `[UInt8]`. This also came with changes to the serialization protocols.
Modifications:
- Add a thin adapter type to bridge between gRPC and Protobuf contiguous bytes
- Adopt new protocols
Result:
Builds again
=> Adopt new serializer protocols

Plugins/PluginsShared/PluginUtils.swift
Xcode provides paths to executables as strings referencing environment variables and then passes those strings to the build plugin as URLs. This meant that when we converted these URLs to strings they percent-encoded some characters and were no longer valid paths e.g.
```
/${BUILD_DIR}/${CONFIGURATION}/protoc-gen-swift
```
became
```
/$%7BBUILD_DIR%7D/$%7BCONFIGURATION%7D/protoc-gen-swift
```
Have our utility function for accessing absolute paths as strings strip percent-encoding.
The build plugin works in Xcode
=> Remove percent-encoded chars in build plugin paths

Plugins/PluginsShared/PluginError.swift
Motivation:
The plugin error case for an incompatible target has an associated value which is currently ignored.
Modifications:
- Use the value
Result:
Fewer warnings
=> Fix warnings about unused value in plugin error

Package.swift, Sources/GRPCProtobufCodeGen/ProtobufCodeGenParser.swift, Sources/GRPCProtobufCodeGen/ProtobufCodeGenerator.swift, Sources/protoc-gen-grpc-swift/GenerateGRPC.swift, Tests/GRPCProtobufCodeGenTests/ProtobufCodeGenParserTests.swift, Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift, Tests/GRPCProtobufCodeGenTests/Utilities.swift
Motivation:
We renamed a few types/properties in the code gen module and deprecated the old names.
Modifications:
- Use new APIs
Result:
No warnings
=> Fix deprecations from codegen changes

Sources/GRPCProtobuf/Documentation.docc/Articles/Installing-protoc.md, Sources/GRPCProtobuf/Documentation.docc/Documentation.md
Motivation:
The official instructions for installing `protoc` don't include instructions for using a package manager. A number of our docs refernce having `protoc` installed as a prerequisite, it'd be useful to have docs on how to install using a package manager.
Modifications:
- Add a doc about installing protoc
Result:
More docs
=> Add an article explaining how to install `protoc`

Plugins/GRPCProtobufGenerator/BuildPluginConfig.swift, Plugins/PluginsShared/GenerationConfig.swift, Plugins/PluginsShared/PluginUtils.swift
Motivation:
When the plugin was done we went through a few iterations of the shape of config and settled on `accessLevelOnImports` vs. `useAccessLevelOnImports` but that change wasn't made.
Modifications:
- Update config name.
Result:
API is what we planned it to be.
=> Align on config name for use import access level

.github/workflows/main.yml, .github/workflows/pull_request.yml
Motivation:
It is no longer required.
Modifications:
Remove explicit 'GITHUB_ACTIONS=true' from workflows, it's now set automatically.
Result:
Clearer config.
=> Remove explicit 'GITHUB_ACTIONS=true'

Sources/protoc-gen-grpc-swift/GenerateGRPC.swift, Sources/protoc-gen-grpc-swift/Options.swift
Motivation:
v1 generated reflection data via the protoc plugin; this wasn't remvoed from v2 but the v2 reflection servcice doesn't use data in the same format. Instead, v2 expects users to invoke protoc directly to generate a descriptor set. This makes the option redundant: it can be called but the output can't be used.
Modifications:
- Remove the reflection data generating code and have the option throw an error.
Result:
Less code
=> Don't generate reflection data.

Package.swift, Plugins/GRPCProtobufGeneratorCommand/Plugin.swift
Motivation:
The command plugin needs to be a product in order for it to be used.
Modifications:
- Add it to the products
- Give it the same name as the command, otherwise diagnostics (like SwiftPM asking for permission to write to the package dir) will use a different name which isn't obvious.
- Fix a few build warnings.
Result:
- Command plugin can be used
=> Add command plugin to package products

Sources/GRPCProtobuf/Errors/GoogleRPCStatus.swift, Sources/GRPCProtobuf/Errors/RPCError+GoogleRPCStatus.swift, Tests/GRPCProtobufTests/Errors/DetailedErrorTests.swift
Motivation:
The 'rich' error model packs a google.rpc.status protobuf message into the trailing metadata of an RPC. This should just be the base64 encoded bytes of the serialzed message. At the moment this is packed within a google.protobuf.any and then added to the metadata which doesn't interop well with other languages.
Modifications:
- Remove the indirection
- Add methods for serializing/deserializing the RPC status wrapper
Result:
Better interop
=> Fix GoogleRPCStatus encoding/decoding

Sources/GRPCProtobuf/Errors/GoogleRPCStatus.swift
Motivation:
GoogleRPCStatus should be hashable: all of its properties already are.
Modifications:
- Add missing Hashable conformance
- Fix incorrect doc
Result:
GoogleRPCStatus is Hashable
=> Make GoogleRPCStatus Hashable

Sources/GRPCProtobuf/Documentation.docc/Articles/Generating-stubs.md
Motivation:
The "PathToUnderscores" options was incorrectly spelled "PathToUnderscore"
in the docs.
Motivation:
- Add the missing "s"
Result:
More accurate docs.
=> Fix typo in docs

Package.swift, Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
Motivation:
grpc-swift 2.2.0 adds availability annotations to generated code. Tests are now failing because they aren't expecting the annotations.
Modifications:
- Update min required version
- Update expectations in tests
Result:
Tests pass
=> Update expected generated code

.github/workflows/main.yml, .github/workflows/pull_request.yml, Tests/GRPCProtobufCodeGenTests/ProtobufCodeGenParserTests.swift, Tests/GRPCProtobufCodeGenTests/Utilities.swift
Motivation:
Swift 6.1 emits a few new warnings from Swift Testing
Modifications:
- Remove redundant `#require` macros
- Enable warnings as errors in CI
- Remove `-require-explicit-sendable` as it wasn't enabled correctly (it requires `-Xfrontend` and is currently incompatible with `-warnings-as-errors`)
Result:
Fewer warnings
=> Fix a few warnings

Tests/GRPCProtobufTests/Errors/Generated/error-service.grpc.swift
Motivation:
The generated code used in tests is out of date. This happened because of an update to grpc-swift and the GitHub actions job to check generated code wasn't a required status check (but now is).
Modifications:
- Regenerate generated code
Result:
Generated code check passes
=> Regenerate code for tests

.github/workflows/pull_request.yml, .github/workflows/soundness.yml, Package.swift, Sources/CGRPCProtobuf/CGRPCProtobuf.c, Sources/CGRPCProtobuf/include/CGRPCProtobuf.h, Sources/protoc-gen-grpc-swift/Version.swift
Motivation:
The version for the package included in protoc-gen-grpc-swift is updated manually and is currently incorrect. We can get the appropriate information from the context provided by SwiftPM.
Modifications:
- Add a C shim module which provides a version string from the package context
Result:
- Version string is kept up-to-date
- Resolves #60
=> Set version info using info from the package context

Sources/GRPCProtobuf/Documentation.docc/Articles/Generating-stubs.md, Sources/GRPCProtobufCodeGen/ProtobufCodeGenerator.swift, Sources/protoc-gen-grpc-swift/GenerateGRPC.swift, Sources/protoc-gen-grpc-swift/Options.swift, Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
Motivation:
grpc-swift 2.2.0 generates code with `@available` annotations. Sometimes it's necessary to raise these.
Modifications:
- Add an `Availability` option to the code generator which, if set at least once overrides the default availability.
- Update docs
Result:
Availability can be configured using `protoc-gen-grpc-swift`
=> Support availability overrides

.github/workflows/main.yml, .github/workflows/pull_request.yml, Package.swift, Sources/GRPCProtobuf/Coding.swift, Sources/GRPCProtobuf/ContiguousBytesAdapter.swift, Sources/GRPCProtobuf/Errors/ErrorDetails+AnyPacking.swift, Sources/GRPCProtobuf/Errors/ErrorDetails+CustomStringConvertible.swift, Sources/GRPCProtobuf/Errors/ErrorDetails+Types.swift, Sources/GRPCProtobuf/Errors/ErrorDetails.swift, Sources/GRPCProtobuf/Errors/GoogleRPCStatus.swift, Sources/GRPCProtobuf/Errors/RPCError+GoogleRPCStatus.swift, Sources/GRPCProtobufCodeGen/ProtobufCodeGenParser.swift, Sources/GRPCProtobufCodeGen/ProtobufCodeGenerator.swift, Sources/protoc-gen-grpc-swift/GenerateGRPC.swift, Sources/protoc-gen-grpc-swift/Options.swift, Tests/GRPCProtobufCodeGenTests/ProtobufCodeGenParserTests.swift, Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift, Tests/GRPCProtobufCodeGenTests/Utilities.swift, Tests/GRPCProtobufTests/Errors/DetailedErrorTests.swift, Tests/GRPCProtobufTests/Errors/Generated/error-service.grpc.swift, Tests/GRPCProtobufTests/ProtobufCodingTests.swift, dev/protos/generate.sh
Motivation:
It's hard for packages to incrementally adopt gRPC with platforms in the package manifest as it requires packages to include platforms in their manifest or mint a new major version.
Modifications:
- Move platform availability onto source code
- Check annotations in CI
Result:
Easier to adopt
=> Move availability inline

Sources/GRPCProtobuf/Coding.swift, Sources/GRPCProtobuf/Errors/GoogleRPCStatus.swift
Motivation:
gRPC Swift v2 has moved to a new repo, grpc-swift-2 and as a result this package has a new major version. That's not all that discoverable.
Modifications:
Deprecate commonly used high-level types with a link to a forums post explaining the move.
Result:
Users are notified about the move
=> Add deprecation warnings

Sources/GRPCProtobuf/Documentation.docc/Articles/Public-services-with-private-implementations.md, Sources/GRPCProtobuf/Documentation.docc/Documentation.md
Motivation:
Sometimes libraries want to vend a public gRPC service but without exposing the generated types as part of the public API. This is easy to achieve but non-obvious.
Modifications:
- Add an article explaining how to achieve this
Result:
Easier for users to learn how to do this
=> Document how to create a public service with private implementation

Plugins/GRPCProtobufGeneratorCommand/CommandConfig.swift, Plugins/GRPCProtobufGeneratorCommand/CommandPluginError.swift, Plugins/GRPCProtobufGeneratorCommand/Plugin.swift
Motivation:
The command plugin has a few rough edges which make it harder to use than it should.
Modifications:
- Check if help was requested before doing any other arg parsing. 
- Print help if no arguments were passed at all.
- Check all input files end in '.proto', if they don't it's likely an option was passed in the wrong place, so print a helpful error message.
- Change the default output path to be ".", i.e. the directory of the caller. Previously it was the plugin working directory which is buried in '.build' so it would appear as if nothing was generated.
- Improve the formatting of the error message if the protoc invocation failed. The error message now includes a better formatted command that the user can invoke directly. Remove the error description because it was always …
=> Fix some papercuts with the command plugin

Plugins/PluginsShared/PluginUtils.swift
Motivation:
protoc requires the import path (-I/--import-path) to be an exact prefix of the input files. The plugin currently uses the absolute path of a file for input paths without modifying the import path.
The result of this is that the user must always specify an absolute import path (because the default chosen by is protoc is ".").
Modifications:
- Use the relative path for input files (this will be whatever the user provides, which may be an absolute path) rather than the absolute path which will get the full absolute path even if the user specified "foo.proto" as input.
Result:
Users can do: swift package generate-grpc-code-from-protos foo.proto
=> Use relative path for input files to protoc

Plugins/GRPCProtobufGeneratorCommand/CommandPluginError.swift, Plugins/GRPCProtobufGeneratorCommand/Plugin.swift
Motivation:
The command plugin had a couple of warnings as vars weren't mutated.
Modifications:
- Change some vars to lets
- Remove an unused string
Result:
No warnings
=> Fix warnings in command plugin
